### PR TITLE
Minor style fixes.

### PR DESCRIPTION
**Pull request by consolegrl**
@DanielKauss just a couple of style fixes, nothing major.

### CODE REVIEW

**Comment by consolegrl** [comment]
I've taken an artistic eye to the plugin artwork and fixed the clipping issues I found. Here is my result.

slicert-update

It was difficult to adjust things without the original layered artwork file, but I did a passable job with the resources available. I would consider it a rough redraft until I can get my hands on the original/layered artwork. If it's not available I could put more effort into adjusting the pixels or even redrafting it if need be.

Anyway I hope you like my artistic re-balancing.

**Comment by DanielKauss** [comment]
Style changes are ok. The original .xcf file of the artwork is in [this PR](https://github.com/LMMS/artwork/pull/22), so I'll wait till you do the final changes to the artwork before merging. Don't really have any complaints, but you should probably put your finished artwork touch up on the main PR for other people to see and discuss.

Btw sorry for not seeing your previous PR, i didn't get notified for some reason.

**Comment by consolegrl** [comment]
> The original .xcf file of the artwork is in [this PR](https://github.com/LMMS/artwork/pull/22), so I'll wait till you do the final changes to the artwork before merging.

@DanielKauss So that XCF is quite a bit farther off than what you had for bg.png, any chance you can upload the XCF you used for the bg.png thats in HEAD of your branch?

**Comment by consolegrl** [comment]
@DanielKauss I uploaded the new good draft of the artwork (and renamed bg to artwork to be consistent with other plugins), the preview is over on the main PR #6857

**Comment by DanielKauss** [comment]
> @DanielKauss So that XCF is quite a bit farther off than what you had for bg.png, any chance you can upload the XCF you used for the bg.png thats in HEAD of your branch?

I just send saker the current version of the artwork in the #dev-only channel on discord, and he said he'll update the PR once the final design is settled. So you can just grab it from discord atm.

**Comment by consolegrl** [comment]
@DanielKauss I pulled it from that PR and was able to construct the current state from it in nice layers, no problems. I've submitted my version as artwork.xcf along with artwork.png which was bg.png (for consistency with other plugins).

Here is the new good draft for reference.
slicert-update

**Comment by DanielKauss** [comment]
Looks good now. Do you want to add anything else or should I merge?

**Comment by consolegrl** [comment]
> Looks good now. Do you want to add anything else or should I merge?

Needs just a bit more balancing but I don't have time just now, but if you like the state right now you can merge it.  I can just push another PR once I do the minor balance adjustments.

**Comment by DanielKauss** [comment]
I'll merge it right now then, you can just open another PR for whatever else you want to adjust.

**Pull request merged**
